name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-20.04
    steps:
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v1.1.11
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y flex bison
      - name: Compile submission
        run: make
      - name: Run tests
        run: ./runtests.sh
